version: '3.8'

services:
  opensuse:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./opensuse
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_RELEASE_TYPE_AND_TAG=${BASE_IMAGE_RELEASE_TYPE_AND_TAG}
        - USER_NAME=${USER_NAME}
    volumes:
      - home:/home
    user: ${USER_NAME}
    stdin_open: true
    tty: true

volumes:
  home:
    name: ${VOLUME_NAME}

networks:
  default:
    name: ${NETWORK_NAME}
